# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-24 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0002_dict_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dict',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dict',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='dictapp/images/', width_field='width_field'),
        ),
    ]
