# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-12 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictapp', '0008_auto_20171205_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
