# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-05 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import introapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro_BW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='티벳어 표제어')),
                ('text', models.TextField(blank=True, null=True, verbose_name='단어설명')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=introapp.models.upload_path_img, verbose_name='사진자료', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=introapp.models.upload_path_file, verbose_name='파일')),
                ('audio', models.FileField(blank=True, null=True, upload_to=introapp.models.upload_path_audio, verbose_name='티벳어 발음 오디오')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('ti_future_tense', models.CharField(blank=True, max_length=200, null=True, verbose_name='동사-미래형')),
                ('ti_present_tense', models.CharField(blank=True, max_length=200, null=True, verbose_name='동사-현재형')),
                ('ti_past_tense', models.CharField(blank=True, max_length=200, null=True, verbose_name='동사-과거형')),
                ('ti_imperative', models.CharField(blank=True, max_length=200, null=True, verbose_name='동사-명령형')),
                ('ti_synonym', models.CharField(blank=True, max_length=200, null=True, verbose_name='동의어')),
                ('ti_thesaurus', models.CharField(blank=True, max_length=200, null=True, verbose_name='유의어')),
                ('ti_antonym', models.CharField(blank=True, max_length=200, null=True, verbose_name='반의어')),
                ('ti_honorific', models.CharField(blank=True, max_length=200, null=True, verbose_name='높임말')),
                ('ti_humble_terms', models.CharField(blank=True, max_length=200, null=True, verbose_name='낮춤말')),
                ('ti_korean_entry', models.CharField(blank=True, max_length=200, null=True, verbose_name='한국어 표제어')),
                ('ti_sanskrit_entry', models.CharField(blank=True, max_length=200, null=True, verbose_name='산스끄리뜨')),
                ('ti_pali_entry', models.CharField(blank=True, max_length=200, null=True, verbose_name='빨리어')),
                ('ti_classical_chinese_entry', models.CharField(blank=True, max_length=200, null=True, verbose_name='한문')),
                ('ti_english_entry', models.CharField(blank=True, max_length=200, null=True, verbose_name='영어')),
                ('ti_wylie', models.CharField(blank=True, max_length=200, null=True, verbose_name='티벳어 와일리표기')),
                ('classification', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2, verbose_name='단어 분류')),
                ('bu_classification', models.CharField(choices=[('《경장》', '《경장》'), ('《율장》', '《율장》'), ('《논장》', '《논장》'), ('《주석》', '《주석》'), ('《찬가》', '《찬가》'), ('《서신》', '《서신》'), ('《시문》', '《시문》'), ('《역사》', '《역사》'), ('《우화》', '《우화》'), ('《인명》', '《인명》'), ('《지명》', '《지명》'), ('《의례》', '《의례》'), ('《복식》', '《복식》'), ('《사원》', '《사원》')], default='FR', max_length=10, verbose_name='불교 단어 분류')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
