# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-08 08:45
from __future__ import unicode_literals

import bookapp.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication_BW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('re_draft_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('main_author', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='주저자 이름')),
                ('main_author_profile', models.TextField(blank=True, default='', null=True, verbose_name='주저자 약력')),
                ('main_author_img', models.ImageField(blank=True, default='', height_field='height_field', null=True, upload_to=bookapp.models.upload_path_main_author_img, verbose_name='주저자-사진', width_field='width_field')),
                ('annotator', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='주석자 이름')),
                ('annotator_profile', models.TextField(blank=True, default='', null=True, verbose_name='주석자 약력')),
                ('annotator_img', models.ImageField(blank=True, default='', height_field='height_field', null=True, upload_to=bookapp.models.upload_path_main_author_img, verbose_name='주석자-사진', width_field='width_field')),
                ('main_translator', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='주저자 이름')),
                ('main_translator_profile', models.TextField(blank=True, default='', null=True, verbose_name='주번역자 약력')),
                ('main_translator_img', models.ImageField(blank=True, default='', height_field='height_field', null=True, upload_to=bookapp.models.upload_path_main_translator_img, verbose_name='주번역자-사진', width_field='width_field')),
                ('co_author', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='다중저자-목록')),
                ('co_translator', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='다중역자-목록')),
                ('co_writer_profile', models.TextField(blank=True, default='', null=True, verbose_name='다중 저자/역자 - 약력')),
                ('editor', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='편집자')),
                ('production_company', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='제작사')),
                ('publisher', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='발행자')),
                ('publishing_company', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='출판사')),
                ('contributor', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='후원자')),
                ('helper', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='기여자')),
                ('copyright_holder', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='판권소유자')),
                ('illustrator', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='삽화가')),
                ('published_date', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='출판일')),
                ('page_num', models.IntegerField(blank=True, default=1, null=True, verbose_name='페이지수')),
                ('isbn', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='ISBN')),
                ('revised_date', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='개정일')),
                ('subject', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='분야')),
                ('edition', models.IntegerField(blank=True, default=1, null=True, verbose_name='판형')),
                ('printing', models.IntegerField(blank=True, default=1, null=True, verbose_name='쇄')),
                ('collection_title', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='컬렉션 제목')),
                ('main_title', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='주제목')),
                ('sub_title', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='부제목')),
                ('introduction', models.TextField(blank=True, default='', null=True, verbose_name='책소개')),
                ('table_of_contents', models.TextField(blank=True, default='', null=True, verbose_name='목차')),
                ('cover_img', models.ImageField(blank=True, default='', height_field='height_field', null=True, upload_to=bookapp.models.upload_path_cover_img, verbose_name='표지-사진', width_field='width_field')),
                ('preview_img_1', models.ImageField(blank=True, default='', height_field='height_field', null=True, upload_to=bookapp.models.upload_path_preview_img, verbose_name='책내용_미리보기_사진1', width_field='width_field')),
                ('preview_img_2', models.ImageField(blank=True, default='', height_field='height_field', null=True, upload_to=bookapp.models.upload_path_preview_img, verbose_name='책내용_미리보기_사진2', width_field='width_field')),
                ('preview_img_3', models.ImageField(blank=True, default='', height_field='height_field', null=True, upload_to=bookapp.models.upload_path_preview_img, verbose_name='책내용_미리보기_사진3', width_field='width_field')),
                ('volume', models.IntegerField(blank=True, default=1, null=True, verbose_name='권번호')),
                ('topic_keyword', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='주제_키워드')),
                ('sale_check', models.CharField(choices=[('sale_now', '판매중'), ('preparing', '준비중'), ('out_of_print', '절판')], default=('sale_now', '판매중'), max_length=10, verbose_name='판매상태')),
                ('errata', models.TextField(blank=True, default='', null=True, verbose_name='오탈자-정정정보')),
                ('errata_date', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='오탈자수정일')),
                ('video_url', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Vedio_URL')),
                ('wiki_url', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Wiki_URL')),
                ('supplement_file', models.FileField(blank=True, default='', null=True, upload_to=bookapp.models.upload_path_file, verbose_name='부록자료')),
                ('author', models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
