# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-08 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_remove_publication_bw_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication_bw',
            name='our_bank',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='구입문의'),
        ),
        migrations.AddField(
            model_name='publication_bw',
            name='price',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='권번호'),
        ),
        migrations.AddField(
            model_name='publication_bw',
            name='selling_price',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='권번호'),
        ),
        migrations.AddField(
            model_name='publication_bw',
            name='stock_num',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='권번호'),
        ),
    ]
