# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-08 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_publication_bw_draftsman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication_bw',
            name='draftsman',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='북정보 작성자 이름'),
        ),
    ]
