# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-12 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_auto_20171208_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication_bw',
            name='main_translator',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='주번역자 이름'),
        ),
        migrations.AlterField(
            model_name='publication_bw',
            name='price',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='정가'),
        ),
        migrations.AlterField(
            model_name='publication_bw',
            name='published_date',
            field=models.DateTimeField(blank=True, default='', max_length=100, null=True, verbose_name='출판일'),
        ),
        migrations.AlterField(
            model_name='publication_bw',
            name='selling_price',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='판매가'),
        ),
        migrations.AlterField(
            model_name='publication_bw',
            name='stock_num',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='재고수량'),
        ),
    ]
