# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-12 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_auto_20171212_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication_bw',
            name='errata_date',
            field=models.DateTimeField(blank=True, default='', max_length=100, null=True, verbose_name='오탈자수정일'),
        ),
        migrations.AlterField(
            model_name='publication_bw',
            name='revised_date',
            field=models.DateTimeField(blank=True, default='', max_length=100, null=True, verbose_name='개정일'),
        ),
    ]
