# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_auto_20171212_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication_bw',
            name='sale_check',
            field=models.CharField(choices=[('판매중', '판매중'), ('준비중', '준비중'), ('절판', '절판')], default=('판매중', '판매중'), max_length=10, verbose_name='판매상태'),
        ),
    ]
