# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-04 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_auto_20171213_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication_bw',
            name='book_cloud_url',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Book_URL'),
        ),
    ]
