# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-07 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_auto_20180607_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication_bw',
            name='selling_price',
            field=models.CharField(blank=True, default=1, max_length=300, null=True, verbose_name='판매가'),
        ),
    ]
